<a href="https://colab.research.google.com/github/Samruddhi-273/SOC-repo/blob/master/DummyVariables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [53]:
from google.colab import files
uploaded = files.upload()

Saving homeprices.csv to homeprices (6).csv

In [54]:
import pandas as pd
df = pd.read_csv('homeprices.csv')
df.head()

              town  area   price
0  monroe township  2600  550000
1  monroe township  3000  565000
2  monroe township  3200  610000
3  monroe township  3600  680000
4  monroe township  4000  725000

In [55]:
dummies = pd.get_dummies(df.town, dtype=int)
dummies

    monroe township  robbinsville  west windsor
0                 1             0             0
1                 1             0             0
2                 1             0             0
3                 1             0             0
4                 1             0             0
5                 0             0             1
6                 0             0             1
7                 0             0             1
8                 0             0             1
9                 0             1             0
10                0             1             0
11                0             1             0
12                0             1             0

In [56]:
merged = pd.concat([df,dummies],axis='columns')
merged

               town  area   price  monroe township  robbinsville  west windsor
0   monroe township  2600  550000                1             0             0
1   monroe township  3000  565000                1             0             0
2   monroe township  3200  610000                1             0             0
3   monroe township  3600  680000                1             0             0
4   monroe township  4000  725000                1             0             0
5      west windsor  2600  585000                0             0             1
6      west windsor  2800  615000                0             0             1
7      west windsor  3300  650000                0             0             1
8      west windsor  3600  710000                0             0             1
9      robbinsville  2600  575000                0             1             0
10     robbinsville  2900  600000                0             1             0
11     robbinsville  3100  620000                0             1             0
12     robbinsville  3600  695000                0             1             0

In [57]:
final = merged.drop(['town','west windsor'],axis='columns')
final

    area   price  monroe township  robbinsville
0   2600  550000                1             0
1   3000  565000                1             0
2   3200  610000                1             0
3   3600  680000                1             0
4   4000  725000                1             0
5   2600  585000                0             0
6   2800  615000                0             0
7   3300  650000                0             0
8   3600  710000                0             0
9   2600  575000                0             1
10  2900  600000                0             1
11  3100  620000                0             1
12  3600  695000                0             1

In [58]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [59]:
X = final.drop(['price'],axis='columns')
X

    area  monroe township  robbinsville
0   2600                1             0
1   3000                1             0
2   3200                1             0
3   3600                1             0
4   4000                1             0
5   2600                0             0
6   2800                0             0
7   3300                0             0
8   3600                0             0
9   2600                0             1
10  2900                0             1
11  3100                0             1
12  3600                0             1

In [60]:
Y = final.price
Y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [61]:
model.fit(X,Y)

LinearRegression()

In [62]:
model.predict([[2800,0,1]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([590775.63964739])

In [63]:
model.predict([[3400,0,0]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([681241.66845839])

In [64]:
model.score(X,Y) #to know how accurate your model is

0.9573929037221872

In [65]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dfle = df
dfle.town=le.fit_transform(dfle.town)
dfle

    town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [66]:
X = dfle[['town','area']].values
X

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]])

In [67]:
Y = dfle.price
Y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [73]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(), [0])],
    remainder='passthrough'
)

X = ct.fit_transform(X)
X

array([[1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 3.0e+03],
       [1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 3.2e+03],
       [1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 3.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 2.9e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 3.1e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 3.6e+03]])

In [74]:
X = X[:,1:]
X

array([[0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 3.0e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 3.2e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 3.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 4.0e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 2.8e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 3.3e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 2.9e+03],
       [1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 3.1e+03],
       [1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 3.6e+03]])

In [75]:
model.fit(X,Y)

LinearRegression()

In [84]:
model.predict([[1,0,0,0,2800]])

array([591369.3829284])

In [87]:
model.predict([[0,0,0,1,3400]])

array([668101.59105569])

In [81]:
model.score(X,Y)

0.9573929037221874