<a href="https://colab.research.google.com/github/Samruddhi-273/SOC-repo/blob/master/NaiveBayes1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("titanic.csv")
df.head()

Saving titanic.csv to titanic.csv

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0

In [3]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

   Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [4]:
inputs = df.drop('Survived',axis='columns')
target = df.Survived

In [5]:
dummies = pd.get_dummies(inputs.Sex)
dummies.head(3)

   female   male
0   False   True
1    True  False
2    True  False

In [6]:
inputs = pd.concat([inputs,dummies],axis='columns')
inputs.head(3)

   Pclass     Sex   Age     Fare  female   male
0       3    male  22.0   7.2500   False   True
1       1  female  38.0  71.2833    True  False
2       3  female  26.0   7.9250    True  False

In [7]:
inputs.drop(['Sex','male'],axis='columns',inplace=True)
inputs.head(3)

   Pclass   Age     Fare  female
0       3  22.0   7.2500   False
1       1  38.0  71.2833    True
2       3  26.0   7.9250    True

In [8]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [9]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [10]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head()

   Pclass   Age     Fare  female
0       3  22.0   7.2500   False
1       1  38.0  71.2833    True
2       3  26.0   7.9250    True
3       1  35.0  53.1000    True
4       3  35.0   8.0500   False

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs,target,test_size=0.3)

In [12]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [13]:
model.fit(X_train,y_train)

GaussianNB()

In [14]:
model.score(X_test,y_test)

0.7985074626865671

In [15]:
X_test[0:10]

     Pclass        Age     Fare  female
95        3  29.699118   8.0500   False
629       3  29.699118   7.7333   False
746       3  16.000000  20.2500   False
753       3  23.000000   7.8958   False
198       3  29.699118   7.7500    True
580       2  25.000000  30.0000    True
762       3  20.000000   7.2292   False
485       3  29.699118  25.4667    True
766       1  29.699118  39.6000   False
744       3  31.000000   7.9250   False

In [16]:
y_test[0:10]

95     0
629    0
746    0
753    0
198    1
580    1
762    1
485    0
766    0
744    1
Name: Survived, dtype: int64

In [17]:
model.predict(X_test[0:10])

array([0, 0, 0, 0, 1, 1, 0, 1, 0, 0])

In [18]:
model.predict_proba(X_test[:10])

array([[0.966964  , 0.033036  ],
       [0.96690236, 0.03309764],
       [0.95699777, 0.04300223],
       [0.96341935, 0.03658065],
       [0.4865043 , 0.5134957 ],
       [0.25630314, 0.74369686],
       [0.96088527, 0.03911473],
       [0.47638329, 0.52361671],
       [0.69706983, 0.30293017],
       [0.96737578, 0.03262422]])

In [19]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),X_train, y_train, cv=5)

array([0.792     , 0.768     , 0.808     , 0.66935484, 0.78225806])